const { types } = require('./typescript/1_types')
const { rectangle } = require('./typescript/2_interface')
const { membership } = require('./typescript/3_enums')
const { add } = require('./typescript/4_functions')
const { Typescript } = require('./typescript/5_classes')
